apiVersion: v1
kind: ConfigMap

metadata:
  name: "{{ .Release.Name }}-config"

data:
  DB_TYPE: "{{ .Values.dbconfig.dbtype }}"
  METRICS_PULL_INTERVAL: "{{ .Values.deployments.metrics.config.pull_seconds }}"
  DB_URI: "{{ .Values.dbconfig.dburi }}"