apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  "{{ .Release.Name }}-ingress-api"

  # Add annotations from values.yaml
  annotations:
    {{- range $key, $value := .Values.ingress.api.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  rules:
  - host: "{{ .Values.ingress.api.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-api-service"
            port: 
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  "{{ .Release.Name }}-ingress-metrics"
  annotations:
    {{- range $key, $value := .Values.ingress.metrics.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  rules:
  - host: "{{ .Values.ingress.metrics.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-metrics-service"
            port: 
              number: 8080
              