# Configure deployment values for the chart
#
deployments:
  api:
    replicas: 1
    image: ghcr.io/hidracloud/hidra:v1.0.2
    imagePullPolicy: IfNotPresent
    resources: {}
  metrics:
    replicas: 1
    image: ghcr.io/hidracloud/hidra:v1.0.2
    imagePullPolicy: IfNotPresent
    resources: {}
    config:
      pull_seconds: 15
ingress:
  api:
    host: hidra.example.com
    annotations: {}
  metrics:  
    host: metrics.hidra.example.com
    annotations: {}

dbconfig:
  dbtype: mysql
  dburi: "mysql://yourdatabase"