# Configure deployment values for the chart
#
deployments:
  api:
    replicas: 1
    image: ghcr.io/hidracloud/hidra:v1.0.0
    imagePullPolicy: IfNotPresent
    resources: {}
  metrics:
    replicas: 1
    image: ghcr.io/hidracloud/hidra:v1.0.0
    imagePullPolicy: IfNotPresent
    resources: {}
    config:
      pull_seconds: 15
ingress:
  host: metrics.hidra.io

dbconfig:
  dbtype: mysql
  dburi: "mysql://yourdatabase"